services:
- docker

before_install:
- source install.sh

jobs:
    include: 
    - stage: build
      script: bash ./build.sh
    - stage: deploy
      if: branch = master
      script: bash ./deploy.sh
