apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dt-spotify-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - dtspotify.shapingideas.fyi
    secretName: letsencrypt-prod
  rules:
  - host: dtspotify.shapingideas.fyi
    http:
      paths:
      - backend:
          serviceName: dt-spotify
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dt-spotify
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: dt-spotify
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dt-spotify
spec:
  selector:
    matchLabels:
      app: dt-spotify
  replicas: 1
  template:
    metadata:
      labels:
        app: dt-spotify
    spec:
      containers:
      - name: dtspotify
        image: wearebrews/dtspotify
        ports:
        - containerPort: 8080
        env:
        - name: BASE_URL
          value: "http://dtspotify.shapingideas.fyi"
        - name: SPOTIFY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: spotifyclient
              key: id
        - name: SPOTIFY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: spotifyclient
              key: secret
        - name: HOST_PORT
          value: "8080"
